version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: emma
      POSTGRES_PASSWORD: emmapassword 
      POSTGRES_DB: nestdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5499:5432